// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CashFlow } from "./CashFlow";

export interface Account { name: string, balance: number, cash_flows: Array<CashFlow>, start_date: string, end_date: string, }