// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Account } from "./Account";
import type { Portfolio } from "./Portfolio";

export interface InvestedAccount { account: Account, portfolio: Portfolio | null, }