// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvestedAccount } from "./InvestedAccount";
import type { Transfer } from "./Transfer";

export interface Scenario { accounts: Array<InvestedAccount>, start_date: string, end_date: string, transfers: Array<Transfer>, }