// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountBalance } from "./AccountBalance";
import type { Payment } from "./Payment";

export interface SimulationResult { balances: Array<AccountBalance>, uninvested_balances: Array<AccountBalance>, payments: Array<Payment>, }