// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frequency } from "./Frequency";

export interface Transfer { from: string, to: string, frequency: Frequency, start_date: string | null, end_date: string | null, amount: number, }