// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Frequency } from ".././rustTypes/cash";

export interface CashFlow { name: string | null, amount: number, frequency: Frequency, start_date: string | null, end_date: string | null, tax_rate: number, }