// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CashFlow } from "./CashFlow";

export interface Payment { cash_flow: CashFlow, date: string, amount: number, }